<a href="https://colab.research.google.com/github/SoundaryaSarathi/Machine-learning/blob/master/linearreg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#linear regression using gradient descent
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
import matplotlib.pyplot as plt

In [ ]:
class Linreg: 
    def __init__(self,n_features,n_samples,learning_rate=0.01,n_iters=1000):
        self.lr = learning_rate
        self.n_samples=n_samples
        self.n_features=n_features
        self.n_iters = n_iters
        self.weights = np.zeros((1,n_features))
        self.bias = 0
    
    def y_predict(self,x):
        return np.dot(self.weights,x.T)+self.bias
    
    def gradientdescent(self,x,error):
        dw=(1/self.n_samples)*np.dot(error,x)
        #print('dw:',dw,dw.shape)
        db=(1/self.n_samples)*np.sum(error)
        return dw,db
        
    def updateparam(self,dw,db):
        self.weights-=self.lr*dw
        self.bias-=self.lr*db
   
    def fit(self,x,y):
      cost_list=[]
      for i in range(self.n_iters):
        y_predict=self.y_predict(x)
        error=y_predict-y
        cost=(1/2*self.n_samples)*(np.sum(np.square(error)))
        dw,db=self.gradientdescent(x,error)
        self.updateparam(dw,db)
        cost_list.append(cost)
      return cost_list

 

In [ ]:
#generation
x,y=datasets.make_regression(n_samples=100,n_features=2,noise=5)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=123)

#normalize(x_train)
#plotting
#fig=plt.figure()
#ax = plt.axes(projection ="3d")
#ax.scatter3D(x_train[:,0],x_train[:,1],y_train)
#plt.scatter(x_train,y_train)
#plt.show()

n_samples,n_features=x_train.shape
print('y_train:',y_train)
linreg=Linreg(n_features,n_samples,0.01,50)
cost_list=linreg.fit(x_train,y_train)
print('costlist: ',cost_list)
print("weights,bias:",linreg.weights,linreg.bias)



y_train: [ -36.7631513    48.04342655  -50.01052718   34.01645206 -159.39751834
   24.19791753  -32.40767049    3.23414017  -65.05532842   86.79586949
  -33.61112873  115.52129884  143.41607      20.40551351  -52.55210129
   66.44788285 -102.64994222 -104.85498915 -238.70355059   74.7438585
   57.07014001   55.76242313  -58.20921018  -55.41222784   73.57843287
   61.99281711   49.30454537   82.87983234 -220.43802776  144.01235785
  127.30153584   23.04249629   -0.36993704   -1.52067456   18.20891029
  -11.45032783 -113.10324191   79.06827189   62.67044217  -77.37722027
  106.66292436  -74.11861949  147.41724596 -161.09775188   27.55694436
 -166.05882303    9.04510738  -17.0743485   -50.63745379  -38.26333844
  -79.11077381   73.96912892  -53.71053362 -255.62840028   42.78906751
  120.98438567    8.78642227   -5.26749317  237.88567093   26.85573886
   98.11310179  195.02811482   66.5951873    77.10176039  -58.38283619
  -55.73094013  -55.54069406   27.43798526  -64.50149152   40.7483348

In [ ]:

#illustrating addition of vector to a scalar
w=np.array([[1,1],[2,2]])
z=w+3
print(z)



[[4 4]
 [5 5]]


In [ ]:
import numpy as np
a = np.array([5,4])[np.newaxis]
print(a)
print(a.T)


[[5 4]]
[[5]
 [4]]
